[platformio]
src_dir = ../../../mcu_balance_fusion_wireless/firmware/src

[env:blackpill_f401cd_profile]
platform = ststm32
board = genericSTM32F401CD
framework = arduino
upload_protocol = stlink
board_build.f_cpu = 84000000L
build_flags =
  -DHAL_UART_MODULE_ENABLED
  -DENABLE_HWSERIAL1
  -DENABLE_HWSERIAL2
  -DENABLE_HWSERIAL6
  -DENABLE_TICK_PROFILER=1
  -DSERIAL_TX_BUFFER_SIZE=384
  -DSERIAL_RX_BUFFER_SIZE=256
  -Wl,-u,_printf_float
  -Wl,--relax
