[env:blackpill_f401cd]
platform = ststm32
board = genericSTM32F401CD
framework = arduino
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200
board_build.f_cpu = 84000000L
build_flags =
    -DHAL_UART_MODULE_ENABLED
    -DENABLE_HWSERIAL1
    -DENABLE_HWSERIAL6
